### ISSUE TITLE
Move to Affero GPL from regular GPL

### ISSUE THREAD

**Issue by synzr** [archive-station/toro#1]
Why? Affero GPL is modified version of GPL. It has extra requirement that perfectly fits for server-side software:

> If you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.

More [here](https://www.gnu.org/licenses/why-affero-gpl.en.html).

_**P.S.** If we change the license, then all code created before the license change will still be under the GPL license._

**Comment by yeeterlol** [comment]
so should we just rewrite the entire thing and then set the Affero GPL license or should we just change it

**Comment by synzr** [comment]
just change it the license in repository. i don't think that current codebase will be that much useful to do the proprietary fork from current state.

**Comment by yeeterlol** [comment]
moved to Affero GPL
